#ifndef _CUDS_VERSION_H
#define _CUDS_VERSION_H

#define CUDS_VERSION_MAJOR 0
#define CUDS_VERSION_MINOR 1
#define CUDS_VERSION_PATCH 0

#define CUDS_VERSION_ENCODE(major, minor, patch) ((major) * 10000 + (minor) * 100 + (patch))
#define CUDS_VERSION_CODE CUDS_VERSION_ENCODE(CUDS_VERSION_MAJOR, CUDS_VERSION_MINOR, CUDS_VERSION_PATCH)

#define CUDS_VERSION_STRING "0.1.0"

#endif // _CUDS_VERSION_H
